vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Oct 2005 03:30:59 -0000
vti_extenderversion:SR|4.0.2.8912
vti_filesize:IR|2407
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5 GENERATOR Microsoft\\ FrontPage\\ 4.0
vti_generator:SR|Microsoft FrontPage 4.0
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|16 Oct 2005 09:52:46 -0000
vti_author:SR|TANG
vti_modifiedby:SR|TANG
vti_timecreated:TR|22 Oct 2005 03:30:59 -0000
vti_cacheddtm:TX|22 Oct 2005 03:30:59 -0000
vti_cachedlinkinfo:VX|S|bg\\ flowers1.bmp A|<%=Myself%>
vti_cachedsvcrellinks:VX|NSUS|Hmath-1t/TBKI-1/bg\\ flowers1.bmp UAUS|<%=Myself%>
vti_cachedbodystyle:SR|<body background="bg%20flowers1.bmp">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
