vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|24 Jan 2007 08:44:09 -0000
vti_extenderversion:SR|4.0.2.8912
vti_filesize:IR|2594
vti_title:SR|
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5 GENERATOR Microsoft\\ FrontPage\\ 4.0
vti_generator:SR|Microsoft FrontPage 4.0
vti_backlinkinfo:VX|hmath-1/tbkin/indxbook.htm
vti_nexttolasttimemodified:TR|21 Feb 2006 10:27:37 -0000
vti_author:SR|123
vti_modifiedby:SR|123
vti_timecreated:TR|24 Jan 2007 08:44:09 -0000
vti_cacheddtm:TX|24 Jan 2007 08:44:09 -0000
vti_cachedlinkinfo:VX|S|../hmath/bg\\ flowers1.bmp A|<%=Myself%>
vti_cachedsvcrellinks:VX|NSUS|Hmath-1/hmath/bg\\ flowers1.bmp UAUS|<%=Myself%>
vti_cachedtitle:SR|
vti_cachedbodystyle:SR|<body background="../hmath/bg%20flowers1.bmp">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
